// Dog-zone layer for the explorer map. Geometry is generated by
// pipeline/index/zones.py (OSM polygons, simplified); each zone's policy
// classification comes from the catalog's verified records, not OSM tags.
import fs from 'node:fs';
import path from 'node:path';
import { DATA_DIR } from './config';

export type ZoneFeature = {
  type: 'Feature';
  properties: {
    id: string;
    name: string;
    kind?: 'trail';
    policy: 'no-dogs' | 'off-leash' | 'leashed' | 'restricted';
    note: string;
    source_url: string;
    venue: string | null;
    acres: number | null;
    miles?: number | null;
    approx: boolean;
    osm: string | null;
  };
  geometry: {
    type: 'Polygon' | 'MultiPolygon' | 'LineString' | 'MultiLineString';
    coordinates: unknown;
  };
};

export type ZoneCollection = {
  type: 'FeatureCollection';
  attribution: string;
  features: ZoneFeature[];
};

export function getTownZones(slug: string): ZoneCollection | null {
  const file = path.join(DATA_DIR, 'cities', slug, 'zones.geojson');
  if (!fs.existsSync(file)) return null;
  const zones = JSON.parse(fs.readFileSync(file, 'utf8')) as ZoneCollection;
  return zones.features.length > 0 ? zones : null;
}
